# Generated by Django 3.1.7 on 2021-03-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210327_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirm_email',
            field=models.BooleanField(default=False, verbose_name='Пользователь подтвержден'),
        ),
    ]
